### ISSUE TITLE
disallow-placementrules.yaml missing "any" keyword

### ISSUE THREAD

**Issue by jwilms1971** [ch-stark/gitops-rbac-example#11]
Missing the "any" keyword after "match", i.e., 

    match:
      any:
      - resources:
          kinds:
          - apps.open-cluster-management.io/v1/PlacementRule

**Comment by ch-stark** [comment]
thanks @jwilms1971 I'll review and change

**Comment by ch-stark** [comment]
fixed it, thanks @jwilms1971
